/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

const golioth_exploration = [
  {
    type: 'autogenerated',
    dirName: 'golioth-exploration',
  },
]

const api_training = [
  {
    type: 'autogenerated',
    dirName: 'api-training',
  },
]

const zephyr_training = [
  {
    type: 'autogenerated',
    dirName: 'zephyr-training',
  },
]

module.exports = {
  golioth_exploration,
  api_training,
  zephyr_training,
};
